name = "cengli"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# Setelah `wrangler d1 create cengli`, ganti database_id dengan id yang muncul.
[[d1_databases]]
binding = "DB"
database_name = "cengli"
database_id = "98583129-1d12-486c-9c4e-274daee5782b"
migrations_dir = "migrations"
