-- Kategori Pacaran + kasus contoh untuk kategori baru (Suami Istri, Kuliah, Sekolah, Pacaran).
-- Jalankan setelah 0004. Kasus contoh ditandai author_id = 'seed'.
-- Hapus semua contoh kapan saja: DELETE FROM scenarios WHERE author_id = 'seed';

INSERT OR IGNORE INTO categories (name, slug, status, sort, created_at) VALUES
  ('Pacaran', 'pacaran', 'published', 15, 0);

INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Suami baru bilang mau kasih uang bulanan ke orang tuanya lebih besar dari ke orang tuaku. Katanya "kan aku yang cari nafkah". Adil nggak?', 'published', 'seed', 1700000036000, (SELECT id FROM categories WHERE slug = 'suami-istri'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Istri minta semua gaji suami dipegang dia, dan suami dikasih uang jajan harian. Suami merasa nggak dipercaya. Adil nggak?', 'published', 'seed', 1700000037000, (SELECT id FROM categories WHERE slug = 'suami-istri'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Aku sengaja diam dua hari setelah bertengkar supaya pasangan sadar sendiri salahnya. Dia bilang itu manipulatif. Wajar nggak?', 'published', 'seed', 1700000038000, (SELECT id FROM categories WHERE slug = 'suami-istri'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Suami pulang kerja langsung main game berjam-jam, sementara aku urus anak sendirian padahal aku juga kerja. Adil nggak?', 'published', 'seed', 1700000039000, (SELECT id FROM categories WHERE slug = 'suami-istri'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Kerja kelompok berlima, dua orang cuma numpang nama, tapi dosen kasih nilai sama rata. Adil nggak?', 'published', 'seed', 1700000040000, (SELECT id FROM categories WHERE slug = 'kuliah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Dosen bilang kuis susulan tidak ada, padahal aku absen karena sakit dan ada surat dokter. Adil nggak?', 'published', 'seed', 1700000041000, (SELECT id FROM categories WHERE slug = 'kuliah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Temanku pinjam catatan kuliahku sebelum ujian, lalu nilainya lebih tinggi dariku. Salah nggak kalau aku kesal?', 'published', 'seed', 1700000042000, (SELECT id FROM categories WHERE slug = 'kuliah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Aku diminta jadi ketua kelompok tapi semua keputusan akhirnya tetap ditolak anggota. Kalau nilai jelek, aku yang disalahkan. Adil nggak?', 'published', 'seed', 1700000043000, (SELECT id FROM categories WHERE slug = 'kuliah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Guru menghukum seluruh kelas karena ada satu murid yang berisik, padahal pelakunya nggak ketahuan. Adil nggak?', 'published', 'seed', 1700000044000, (SELECT id FROM categories WHERE slug = 'sekolah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Nilai ulanganku turun tiga poin karena telat kumpul lima menit, padahal jawabannya benar semua. Adil nggak?', 'published', 'seed', 1700000045000, (SELECT id FROM categories WHERE slug = 'sekolah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Teman sebangku selalu nyontek PR-ku, dan kalau aku tolak dia mengancam nggak mau berteman lagi. Salah nggak kalau aku tolak?', 'published', 'seed', 1700000046000, (SELECT id FROM categories WHERE slug = 'sekolah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Kelas kami disuruh iuran untuk kado guru, tapi ada yang bilang nggak usah ikut kalau nggak mampu, malah dikucilkan. Adil nggak?', 'published', 'seed', 1700000047000, (SELECT id FROM categories WHERE slug = 'sekolah'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Pacarku minta password HP-ku "biar nggak ada rahasia". Aku nggak nyaman tapi dia bilang kalau nggak salah kenapa takut. Adil nggak?', 'published', 'seed', 1700000048000, (SELECT id FROM categories WHERE slug = 'pacaran'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Kencan pertama aku yang bayar semua, dan pas kencan kedua dia bilang gantian tapi ternyata aku lagi yang bayar. Wajar nggak kalau aku kesal?', 'published', 'seed', 1700000049000, (SELECT id FROM categories WHERE slug = 'pacaran'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Pacarku suka membandingkan aku dengan mantannya sambil bilang "cuma bercanda". Aku bilang nggak lucu. Adil nggak kalau aku minta berhenti?', 'published', 'seed', 1700000050000, (SELECT id FROM categories WHERE slug = 'pacaran'));
INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES ('Aku telat balas chat pacar tiga jam karena sibuk kerja, dia marah dan bilang aku nggak menghargainya. Adil nggak?', 'published', 'seed', 1700000051000, (SELECT id FROM categories WHERE slug = 'pacaran'));
