-- Kategori Belanja Online, Ojol & Delivery, Medsos, Gadget + kasus contoh (juga tambahan kasus Suami Istri).
-- Jalankan setelah 0008. Kasus contoh ditandai author_id = 'seed'.
-- Hapus semua contoh kapan saja: DELETE FROM scenarios WHERE author_id = 'seed';

INSERT OR IGNORE INTO categories (name, slug, status, sort, created_at) VALUES
  ('Belanja Online', 'belanja-online', 'published', 22, 0),
  ('Ojol & Delivery', 'ojol-delivery', 'published', 24, 0),
  ('Medsos', 'medsos', 'published', 26, 0),
  ('Gadget', 'gadget', 'published', 28, 0);

INSERT INTO scenarios (text, status, author_id, created_at, category_id) VALUES
('Pembeli kasih bintang 1 karena "kemasannya kurang cantik", padahal barangnya sampai utuh dan sesuai. Penjual jadi dagang sambil deg-degan. Adil nggak?', 'published', 'seed', 1700000201000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Aku beli sepatu, dipakai dua minggu, lalu minta retur karena "kurang cocok". Penjual menolak. Aku merasa berhak, dia merasa dirugikan. Siapa yang cengli?', 'published', 'seed', 1700000202000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Penjual menolak retur dengan alasan "kemasan sudah dibuka", padahal barangnya cacat dari pabrik. Wajar nggak dia menolak?', 'published', 'seed', 1700000203000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Pesanan COD, kurir sudah sampai depan rumah, tapi aku bilang "nggak jadi". Barangnya sudah diantar jauh-jauh. Salah nggak?', 'published', 'seed', 1700000204000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Flash sale, harga di keranjangku tiba-tiba naik pas checkout. Penjual bilang "itu salah input, batal ya". Aku sudah telanjur bayar. Adil nggak?', 'published', 'seed', 1700000205000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Penjual minta ulasan bintang 5 dengan imbalan diskon di pembelian berikutnya. Aku setuju, tapi barangnya biasa saja. Jujur atau ikut kesepakatan?', 'published', 'seed', 1700000206000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Ongkir barang seharga 20 ribu ternyata 35 ribu. Aku batalin pesanan, penjual marah-marah di chat. Siapa yang salah?', 'published', 'seed', 1700000207000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Aku beli barang bekas dengan deskripsi "mulus 95 persen", ternyata ada baret di mana-mana. Penjual bilang "namanya juga bekas". Wajar nggak?', 'published', 'seed', 1700000208000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Aku titip beli lewat teman yang ngaku "jastip", harganya lebih mahal 30 persen dari toko resmi. Dia bilang itu ongkos capek. Adil nggak?', 'published', 'seed', 1700000209000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Penjual online balas chat cuma "ready kak", lalu menghilang tiga hari. Setelah aku tanya, dia bilang "kan sudah dijawab". Cengli nggak?', 'published', 'seed', 1700000210000, (SELECT id FROM categories WHERE slug = 'belanja-online')),
('Driver minta aku membatalkan order karena "jauh banget", lalu marah waktu aku menolak. Kami sama-sama sudah nunggu lama. Siapa yang salah?', 'published', 'seed', 1700000211000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Makanan sampai telat 40 menit dan sudah dingin, tapi drivernya ramah. Aku nggak kasih tip dan kasih bintang 4. Adil nggak?', 'published', 'seed', 1700000212000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Kurir titip paketku ke satpam tanpa tanya dulu, lalu satpamnya lupa. Kurir bilang "yang penting sudah diantar". Wajar nggak?', 'published', 'seed', 1700000213000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Ojol nggak mau masuk gang sempit dan minta aku jalan kaki 200 meter ke titik jemput. Aku bilang itu bukan tugasku. Adil nggak?', 'published', 'seed', 1700000214000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Aku pesan makan dengan catatan "jangan pedas", yang datang pedas banget. Restoran bilang "tulis catatan sebelum bayar". Siapa yang salah?', 'published', 'seed', 1700000215000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Driver ojol berhenti dulu beli rokok di tengah jalan padahal aku sudah telat meeting. Dia bilang "sebentar doang". Wajar nggak?', 'published', 'seed', 1700000216000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Aku kasih tip 2 ribu ke driver yang ngantar di tengah hujan deras. Dia menatap aku lama. Aku salah atau dia yang berlebihan?', 'published', 'seed', 1700000217000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Alamat pengantaran salah karena aku salah ketik, tapi kurir menyalahkanku di depan tetangga. Aku sudah minta maaf. Wajar nggak dia ngomel?', 'published', 'seed', 1700000218000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Pesanan antar makanan sampai, tapi kurirnya minta uang tambahan "bensin" dengan alasan lokasi jauh. Aku sudah bayar ongkir di aplikasi. Adil nggak?', 'published', 'seed', 1700000219000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Driver mengecek HP terus selama perjalanan dan bilang "lagi cari orderan lain". Aku merasa nggak aman. Wajar nggak aku minta berhenti?', 'published', 'seed', 1700000220000, (SELECT id FROM categories WHERE slug = 'ojol-delivery')),
('Aku screenshot chat pribadi dan kirim ke grup untuk minta pendapat, tanpa nama. Temanku tahu dan marah besar. Cengli nggak?', 'published', 'seed', 1700000221000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Temanku upload fotoku yang lagi bengong tanpa izin, katanya "lucu banget". Aku minta diturunkan, dia malah bilang "baper". Adil nggak?', 'published', 'seed', 1700000222000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Aku keluar dari grup WA keluarga besar tanpa pamit karena sudah terlalu ramai. Sekarang dibilang nggak sopan. Salah nggak?', 'published', 'seed', 1700000223000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Ada yang komentar pedas di postinganku. Aku balas dengan sindiran halus di story tanpa menyebut nama. Wajar nggak?', 'published', 'seed', 1700000224000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Temanku spoiler akhir film di grup, padahal sudah bilang "jangan bahas dulu". Dia bilang filmnya sudah lama. Siapa yang salah?', 'published', 'seed', 1700000225000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Aku like postingan mantan tapi nggak sengaja, pasanganku marah dua hari. Aku merasa berlebihan, dia merasa wajar. Siapa yang benar?', 'published', 'seed', 1700000226000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Pasangan minta password medsos "biar transparan". Aku nggak mau. Aku salah karena menyimpan rahasia atau dia yang kelewat curiga?', 'published', 'seed', 1700000227000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Aku baca pesan teman dan hanya centang biru tanpa membalas selama dua hari. Dia mulai kirim "p" berkali-kali. Siapa yang menyebalkan?', 'published', 'seed', 1700000228000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Kolega nge-tag aku di postingan promosinya tanpa izin. Aku hapus tag-nya, dia sindir di story. Cengli nggak?', 'published', 'seed', 1700000229000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Temanku pamer liburan tiap hari padahal dia masih punya utang ke aku. Wajar nggak kalau aku sindir lewat story?', 'published', 'seed', 1700000230000, (SELECT id FROM categories WHERE slug = 'medsos')),
('Patungan langganan streaming berempat, tapi satu orang pakai 24 jam dan sering ganti profil orang lain. Adil nggak dia bayar sama?', 'published', 'seed', 1700000231000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Aku pinjamkan charger ke teman kantor, tiga bulan belum balik. Dia bilang "kan cuma charger". Wajar nggak aku tagih?', 'published', 'seed', 1700000232000, (SELECT id FROM categories WHERE slug = 'gadget')),
('HP baruku dipegang teman untuk foto, lalu dia buka-buka galeri. Dia bilang "penasaran doang". Salah nggak aku marah?', 'published', 'seed', 1700000233000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Kolega selalu menyalakan speaker HP di ruang kerja bersama untuk dengar video. Aku minta pakai earphone, dia bilang "kan seru". Adil nggak?', 'published', 'seed', 1700000234000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Pasangan beli HP flagship terbaru sementara HP-nya yang lama masih bagus. Aku bilang boros, dia bilang "uang sendiri". Siapa yang benar?', 'published', 'seed', 1700000235000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Temanku pinjam power bank dan mengembalikannya dalam keadaan kosong. Dia bilang "kan tinggal diisi lagi". Wajar nggak?', 'published', 'seed', 1700000236000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Anak temanku ketagihan game dan orang tuanya menyalahkan aku karena mengenalkan. Aku cuma bilang "coba main sebentar". Salah nggak?', 'published', 'seed', 1700000237000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Aku terima update aplikasi yang bikin HP jadi lemot, lalu pabrik bilang "itu memang spesifikasinya". Aku merasa dibohongi. Adil nggak?', 'published', 'seed', 1700000238000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Rekan kerja bilang HP-ku "jadul banget" di depan orang banyak. Aku memilih diam. Aku yang terlalu sensitif atau dia yang kelewatan?', 'published', 'seed', 1700000239000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Teman kos pakai Wi-Fi kos untuk download besar-besaran tiap malam sampai yang lain nggak bisa kerja. Wajar nggak ditegur?', 'published', 'seed', 1700000240000, (SELECT id FROM categories WHERE slug = 'gadget')),
('Istri belanja online terus, katanya "buat kebutuhan rumah". Suami bilang paketnya kebanyakan. Siapa yang cengli?', 'published', 'seed', 1700000241000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami minta jatah "uang rokok" tetap dari gaji, istri bilang rokok itu bukan kebutuhan. Adil nggak?', 'published', 'seed', 1700000242000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Istri bangun lebih siang di hari libur dan suami yang urus sarapan anak. Suami bilang "gantian dong". Istri bilang "kan aku capek kerja". Siapa yang benar?', 'published', 'seed', 1700000243000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami membeli barang mahal untuk hobinya tanpa diskusi dulu, katanya "uang dari bonus sendiri". Istri marah. Wajar nggak?', 'published', 'seed', 1700000244000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Istri bilang mertua terlalu ikut campur urusan rumah tangga. Suami membela ibunya. Siapa yang harus mengalah?', 'published', 'seed', 1700000245000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami selalu bilang "terserah" tiap ditanya mau makan apa, lalu protes kalau pilihannya nggak cocok. Adil nggak?', 'published', 'seed', 1700000246000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Istri menyembunyikan jumlah tabungannya sendiri dari suami "buat jaga-jaga". Suami merasa nggak dipercaya. Siapa yang salah?', 'published', 'seed', 1700000247000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami memaksa pindah ke kota lain karena karier, istri harus resign. Istri nggak keberatan tapi minta imbalan. Adil nggak?', 'published', 'seed', 1700000248000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami lebih sering ngobrol dengan teman game-nya daripada dengan istri. Istri merasa jadi nomor dua. Wajar nggak dia cemburu?', 'published', 'seed', 1700000249000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami dan istri sama-sama kerja, tapi urusan cuci piring selalu jatuh ke istri "karena dia jago". Adil nggak?', 'published', 'seed', 1700000250000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Istri minta dijemput tiap pulang kerja padahal suami baru pulang dari kantor sendiri dan capek. Wajar nggak?', 'published', 'seed', 1700000251000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami tidur pakai AC 18 derajat, istri kedinginan. Suami bilang "kan bisa pakai selimut". Siapa yang harus mengalah?', 'published', 'seed', 1700000252000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Istri membalas semua chat dari teman kerja laki-laki dengan ramah, suami merasa terganggu. Istri bilang itu cuma sopan. Siapa yang benar?', 'published', 'seed', 1700000253000, (SELECT id FROM categories WHERE slug = 'suami-istri')),
('Suami lupa ulang tahun pernikahan, tapi ingat ulang tahun klub bola favoritnya. Wajar nggak istri marah?', 'published', 'seed', 1700000254000, (SELECT id FROM categories WHERE slug = 'suami-istri'));
