-- Semua kasus contoh diakhiri pertanyaan yang cocok dengan pilihan Cengli / Bo Cengli (adil atau wajar nggak),
-- bukan "siapa yang salah". Hanya menyentuh kasus contoh (author_id = 'seed'); suara tetap ikut.

UPDATE scenarios SET text = 'Aku diundang nikahan teman dekat, tapi angpaonya kurang dari yang dia kasih di nikahanku dulu. Wajar nggak?' WHERE author_id = 'seed' AND text = 'Aku diundang nikahan teman dekat, tapi angpaonya kurang dari yang dia kasih di nikahanku dulu. Salah nggak?';
UPDATE scenarios SET text = 'Teman minta aku jadi saksi lomba dadakan hari Minggu, padahal itu satu-satunya hari liburku. Aku nolak. Wajar nggak?' WHERE author_id = 'seed' AND text = 'Teman minta aku jadi saksi lomba dadakan hari Minggu, padahal itu satu-satunya hari liburku. Aku nolak. Salah nggak?';
UPDATE scenarios SET text = 'Tetangga sebelah karaoke sampai jam 11 malam saat ada acara keluarga. Wajar nggak aku minta dikecilkan?' WHERE author_id = 'seed' AND text = 'Tetangga sebelah karaoke sampai jam 11 malam saat ada acara keluarga. Salah nggak aku minta dikecilkan?';
UPDATE scenarios SET text = 'Aku ambil kursi di kereta, lalu ada orang muda yang minta tukar tanpa alasan jelas. Wajar nggak kalau aku tolak?' WHERE author_id = 'seed' AND text = 'Aku ambil kursi di kereta, lalu ada orang muda yang minta tukar tanpa alasan jelas. Salah nggak kalau aku tolak?';
UPDATE scenarios SET text = 'Temanku pinjam catatan kuliahku sebelum ujian, lalu nilainya lebih tinggi dariku. Wajar nggak kalau aku kesal?' WHERE author_id = 'seed' AND text = 'Temanku pinjam catatan kuliahku sebelum ujian, lalu nilainya lebih tinggi dariku. Salah nggak kalau aku kesal?';
UPDATE scenarios SET text = 'Teman sebangku selalu nyontek PR-ku, dan kalau aku tolak dia mengancam nggak mau berteman lagi. Wajar nggak kalau aku tolak?' WHERE author_id = 'seed' AND text = 'Teman sebangku selalu nyontek PR-ku, dan kalau aku tolak dia mengancam nggak mau berteman lagi. Salah nggak kalau aku tolak?';
UPDATE scenarios SET text = 'Ibu kos melarang bawa teman ke kamar setelah jam 9, tapi anaknya boleh bawa pacar sampai tengah malam. Aturannya adil nggak sih?' WHERE author_id = 'seed' AND text = 'Ibu kos melarang bawa teman ke kamar setelah jam 9, tapi anaknya boleh bawa pacar sampai tengah malam. Aturannya cengli nggak sih?';
UPDATE scenarios SET text = 'Jemuran tetangga di lantai atas menetes ke jemuranku yang baru kering. Aku angkat jemuranku, dia malah bilang "kan cuma air". Wajar nggak aku kesal?' WHERE author_id = 'seed' AND text = 'Jemuran tetangga di lantai atas menetes ke jemuranku yang baru kering. Aku angkat jemuranku, dia malah bilang "kan cuma air". Siapa yang salah?';
UPDATE scenarios SET text = 'Teman kos makan lauk dari kulkas bersama tanpa izin, meninggalkan sticky note "makasih ya, enak" di piringnya. Sopan sih, tapi adil nggak?' WHERE author_id = 'seed' AND text = 'Teman kos makan lauk dari kulkas bersama tanpa izin, meninggalkan sticky note "makasih ya, enak" di piringnya. Sopan sih, tapi tetap nggak adil, kan?';
UPDATE scenarios SET text = 'Satu kos pakai satu mesin cuci. Ada yang nyuci jam 2 pagi dan bajunya dibiarkan berhari-hari di dalam mesin. Kami yang lain harus nunggu. Wajar nggak kalau bajunya kami keluarin?' WHERE author_id = 'seed' AND text = 'Satu kos pakai satu mesin cuci. Ada yang nyuci jam 2 pagi dan bajunya dibiarkan berhari-hari di dalam mesin. Kami yang lain harus nunggu. Salah nggak kalau bajunya kami keluarin?';
UPDATE scenarios SET text = 'Tetangga punya ayam jago yang berkokok jam 3 pagi. Aku bilang baik-baik, dia jawab "itu alarm alami, bersyukur dong". Wajar nggak aku bete?' WHERE author_id = 'seed' AND text = 'Tetangga punya ayam jago yang berkokok jam 3 pagi. Aku bilang baik-baik, dia jawab "itu alarm alami, bersyukur dong". Aku boleh nggak bete?';
UPDATE scenarios SET text = 'Aku beli sepatu, dipakai dua minggu, lalu minta retur karena "kurang cocok". Penjual menolak. Aku merasa berhak, dia merasa dirugikan. Adil nggak kalau retur ditolak?' WHERE author_id = 'seed' AND text = 'Aku beli sepatu, dipakai dua minggu, lalu minta retur karena "kurang cocok". Penjual menolak. Aku merasa berhak, dia merasa dirugikan. Siapa yang cengli?';
UPDATE scenarios SET text = 'Pesanan COD, kurir sudah sampai depan rumah, tapi aku bilang "nggak jadi". Barangnya sudah diantar jauh-jauh. Wajar nggak aku batalin?' WHERE author_id = 'seed' AND text = 'Pesanan COD, kurir sudah sampai depan rumah, tapi aku bilang "nggak jadi". Barangnya sudah diantar jauh-jauh. Salah nggak?';
UPDATE scenarios SET text = 'Penjual minta ulasan bintang 5 dengan imbalan diskon di pembelian berikutnya. Aku setuju, tapi barangnya biasa saja. Adil nggak kalau aku tetap kasih bintang 5?' WHERE author_id = 'seed' AND text = 'Penjual minta ulasan bintang 5 dengan imbalan diskon di pembelian berikutnya. Aku setuju, tapi barangnya biasa saja. Jujur atau ikut kesepakatan?';
UPDATE scenarios SET text = 'Ongkir barang seharga 20 ribu ternyata 35 ribu. Aku batalin pesanan, penjual marah-marah di chat. Wajar nggak aku batalin?' WHERE author_id = 'seed' AND text = 'Ongkir barang seharga 20 ribu ternyata 35 ribu. Aku batalin pesanan, penjual marah-marah di chat. Siapa yang salah?';
UPDATE scenarios SET text = 'Driver minta aku membatalkan order karena "jauh banget", lalu marah waktu aku menolak. Kami sama-sama sudah nunggu lama. Wajar nggak aku menolak?' WHERE author_id = 'seed' AND text = 'Driver minta aku membatalkan order karena "jauh banget", lalu marah waktu aku menolak. Kami sama-sama sudah nunggu lama. Siapa yang salah?';
UPDATE scenarios SET text = 'Aku pesan makan dengan catatan "jangan pedas", yang datang pedas banget. Restoran bilang "tulis catatan sebelum bayar". Adil nggak restoran menyalahkan aku?' WHERE author_id = 'seed' AND text = 'Aku pesan makan dengan catatan "jangan pedas", yang datang pedas banget. Restoran bilang "tulis catatan sebelum bayar". Siapa yang salah?';
UPDATE scenarios SET text = 'Aku kasih tip 2 ribu ke driver yang ngantar di tengah hujan deras. Dia menatap aku lama. Wajar nggak aku kasih tip segitu?' WHERE author_id = 'seed' AND text = 'Aku kasih tip 2 ribu ke driver yang ngantar di tengah hujan deras. Dia menatap aku lama. Aku salah atau dia yang berlebihan?';
UPDATE scenarios SET text = 'Aku keluar dari grup WA keluarga besar tanpa pamit karena sudah terlalu ramai. Sekarang dibilang nggak sopan. Wajar nggak aku keluar tanpa pamit?' WHERE author_id = 'seed' AND text = 'Aku keluar dari grup WA keluarga besar tanpa pamit karena sudah terlalu ramai. Sekarang dibilang nggak sopan. Salah nggak?';
UPDATE scenarios SET text = 'Temanku spoiler akhir film di grup, padahal sudah bilang "jangan bahas dulu". Dia bilang filmnya sudah lama. Wajar nggak aku kesal?' WHERE author_id = 'seed' AND text = 'Temanku spoiler akhir film di grup, padahal sudah bilang "jangan bahas dulu". Dia bilang filmnya sudah lama. Siapa yang salah?';
UPDATE scenarios SET text = 'Aku like postingan mantan tapi nggak sengaja, pasanganku marah dua hari. Aku bilang itu nggak sengaja, dia bilang tetap nggak sopan. Wajar nggak dia marah dua hari?' WHERE author_id = 'seed' AND text = 'Aku like postingan mantan tapi nggak sengaja, pasanganku marah dua hari. Aku merasa berlebihan, dia merasa wajar. Siapa yang benar?';
UPDATE scenarios SET text = 'Pasangan minta password medsos "biar transparan". Aku nggak mau. Wajar nggak aku menolak?' WHERE author_id = 'seed' AND text = 'Pasangan minta password medsos "biar transparan". Aku nggak mau. Aku salah karena menyimpan rahasia atau dia yang kelewat curiga?';
UPDATE scenarios SET text = 'Aku baca pesan teman dan hanya centang biru tanpa membalas selama dua hari. Dia mulai kirim "p" berkali-kali. Wajar nggak aku diamkan?' WHERE author_id = 'seed' AND text = 'Aku baca pesan teman dan hanya centang biru tanpa membalas selama dua hari. Dia mulai kirim "p" berkali-kali. Siapa yang menyebalkan?';
UPDATE scenarios SET text = 'HP baruku dipegang teman untuk foto, lalu dia buka-buka galeri. Dia bilang "penasaran doang". Wajar nggak aku marah?' WHERE author_id = 'seed' AND text = 'HP baruku dipegang teman untuk foto, lalu dia buka-buka galeri. Dia bilang "penasaran doang". Salah nggak aku marah?';
UPDATE scenarios SET text = 'Pasangan beli HP flagship terbaru sementara HP-nya yang lama masih bagus. Aku bilang boros, dia bilang "uang sendiri". Wajar nggak aku bilang boros?' WHERE author_id = 'seed' AND text = 'Pasangan beli HP flagship terbaru sementara HP-nya yang lama masih bagus. Aku bilang boros, dia bilang "uang sendiri". Siapa yang benar?';
UPDATE scenarios SET text = 'Anak temanku ketagihan game dan orang tuanya menyalahkan aku karena mengenalkan. Aku cuma bilang "coba main sebentar". Adil nggak aku yang disalahkan?' WHERE author_id = 'seed' AND text = 'Anak temanku ketagihan game dan orang tuanya menyalahkan aku karena mengenalkan. Aku cuma bilang "coba main sebentar". Salah nggak?';
UPDATE scenarios SET text = 'Rekan kerja bilang HP-ku "jadul banget" di depan orang banyak. Aku memilih diam. Wajar nggak aku tersinggung?' WHERE author_id = 'seed' AND text = 'Rekan kerja bilang HP-ku "jadul banget" di depan orang banyak. Aku memilih diam. Aku yang terlalu sensitif atau dia yang kelewatan?';
UPDATE scenarios SET text = 'Istri belanja online terus, katanya "buat kebutuhan rumah". Suami bilang paketnya kebanyakan. Wajar nggak suami protes?' WHERE author_id = 'seed' AND text = 'Istri belanja online terus, katanya "buat kebutuhan rumah". Suami bilang paketnya kebanyakan. Siapa yang cengli?';
UPDATE scenarios SET text = 'Istri bangun lebih siang di hari libur dan suami yang urus sarapan anak. Suami bilang "gantian dong". Istri bilang "kan aku capek kerja". Adil nggak kalau suami minta gantian?' WHERE author_id = 'seed' AND text = 'Istri bangun lebih siang di hari libur dan suami yang urus sarapan anak. Suami bilang "gantian dong". Istri bilang "kan aku capek kerja". Siapa yang benar?';
UPDATE scenarios SET text = 'Istri bilang mertua terlalu ikut campur urusan rumah tangga. Suami membela ibunya. Wajar nggak suami membela ibunya?' WHERE author_id = 'seed' AND text = 'Istri bilang mertua terlalu ikut campur urusan rumah tangga. Suami membela ibunya. Siapa yang harus mengalah?';
UPDATE scenarios SET text = 'Istri menyembunyikan jumlah tabungannya sendiri dari suami "buat jaga-jaga". Suami merasa nggak dipercaya. Wajar nggak istri menyimpannya?' WHERE author_id = 'seed' AND text = 'Istri menyembunyikan jumlah tabungannya sendiri dari suami "buat jaga-jaga". Suami merasa nggak dipercaya. Siapa yang salah?';
UPDATE scenarios SET text = 'Suami tidur pakai AC 18 derajat, istri kedinginan. Suami bilang "kan bisa pakai selimut". Adil nggak kalau istri yang harus mengalah?' WHERE author_id = 'seed' AND text = 'Suami tidur pakai AC 18 derajat, istri kedinginan. Suami bilang "kan bisa pakai selimut". Siapa yang harus mengalah?';
UPDATE scenarios SET text = 'Istri membalas semua chat dari teman kerja laki-laki dengan ramah, suami merasa terganggu. Istri bilang itu cuma sopan. Wajar nggak suami terganggu?' WHERE author_id = 'seed' AND text = 'Istri membalas semua chat dari teman kerja laki-laki dengan ramah, suami merasa terganggu. Istri bilang itu cuma sopan. Siapa yang benar?';
